branches:
    only:
        - 'master'

language: node_js
cache: npm
script: bin/build-lambda
deploy:
    skip_cleanup: true
    provider: lambda
    function_name: 'gh-activity'
    region: 'us-east-1'
    role: 'arn:aws:iam::534616018104:role/service-role/gh-activity-role-y2k32tv5'
    runtime: 'nodejs8.10'
    module_name: 'build'
    handler_name: 'handler'
    timeout: 30
    on:
        branch: master
